name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # 添加环境变量传递配置
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          IMG_BED_URL: ${{ secrets.IMG_BED_URL }}
          AUTH_CODE: ${{ secrets.AUTH_CODE }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}